// Expanded movie dataset for better recommendations
const movies = [
  { id: 1, title: "Inception", genres: ["Action", "Sci-Fi", "Thriller"], tmdbId: 27205 },
  { id: 2, title: "The Matrix", genres: ["Action", "Sci-Fi"], tmdbId: 603 },
  { id: 3, title: "Interstellar", genres: ["Adventure", "Drama", "Sci-Fi"], tmdbId: 157336 },
  { id: 4, title: "The Dark Knight", genres: ["Action", "Crime", "Drama"], tmdbId: 155 },
  { id: 5, title: "Shutter Island", genres: ["Mystery", "Thriller"], tmdbId: 11324 },
  { id: 6, title: "Tenet", genres: ["Action", "Thriller", "Sci-Fi"], tmdbId: 577922 },
  { id: 7, title: "The Prestige", genres: ["Drama", "Mystery", "Thriller"], tmdbId: 1124 },
  { id: 8, title: "Fight Club", genres: ["Drama"], tmdbId: 550 },
  { id: 9, title: "The Social Network", genres: ["Biography", "Drama"], tmdbId: 37799 },
  { id: 10, title: "Parasite", genres: ["Comedy", "Drama", "Thriller"], tmdbId: 496243 },
  { id: 11, title: "Gladiator", genres: ["Action", "Drama", "Adventure"], tmdbId: 98 },
  { id: 12, title: "The Wolf of Wall Street", genres: ["Biography", "Crime", "Drama"], tmdbId: 106646 },
  { id: 13, title: "Memento", genres: ["Mystery", "Thriller"], tmdbId: 77 },
  { id: 14, title: "Baashha", genres: ["Action", "Drama"], tmdbId: null },
  { id: 15, title: "Annamalai", genres: ["Drama", "Action"], tmdbId: null },
  { id: 16, title: "Muthu", genres: ["Action", "Drama"], tmdbId: null },
  { id: 17, title: "Nadodi Mannan", genres: ["Drama"], tmdbId: null },
  { id: 18, title: "Theri", genres: ["Action", "Thriller"], tmdbId: null },
  { id: 19, title: "Kabali", genres: ["Action", "Drama"], tmdbId: null },
  { id: 20, title: "Kaala", genres: ["Crime", "Drama"], tmdbId: null },
  { id: 21, title: "Enthiran", genres: ["Sci-Fi", "Action"], tmdbId: null },
  { id: 22, title: "2.0", genres: ["Sci-Fi", "Action"], tmdbId: null },
  { id: 23, title: "Vikram", genres: ["Action", "Thriller"], tmdbId: null },
  { id: 24, title: "Master", genres: ["Action", "Drama"], tmdbId: null },
  { id: 25, title: "Mersal", genres: ["Drama", "Action"], tmdbId: null },
  { id: 26, title: "Soorarai Pottru", genres: ["Drama"], tmdbId: null },
  { id: 27, title: "Kaakka Muttai", genres: ["Drama"], tmdbId: null },
  { id: 28, title: "Pariyerum Perumal", genres: ["Drama"], tmdbId: null },
  { id: 29, title: "Jigarthanda", genres: ["Crime", "Drama"], tmdbId: null },
  { id: 30, title: "Visaaranai", genres: ["Crime", "Drama"], tmdbId: null },
  { id: 31, title: "Pithamagan", genres: ["Drama"], tmdbId: null },
  { id: 32, title: "Kaadhal", genres: ["Romance", "Drama"], tmdbId: null },
  { id: 33, title: "Roja", genres: ["Romance", "Drama"], tmdbId: null },
  { id: 34, title: "Bombay", genres: ["Romance", "Drama"], tmdbId: null },
  { id: 35, title: "Iruvar", genres: ["Drama", "Political"], tmdbId: null },
  { id: 36, title: "Nayakan", genres: ["Crime", "Drama"], tmdbId: null },
  { id: 37, title: "Thevar Magan", genres: ["Drama"], tmdbId: null },
  { id: 38, title: "Anbe Sivam", genres: ["Drama", "Comedy"], tmdbId: null },
  { id: 39, title: "Sethu", genres: ["Drama", "Romance"], tmdbId: null },
  { id: 40, title: "Autograph", genres: ["Drama"], tmdbId: null },
  { id: 41, title: "Deiva Thirumagal", genres: ["Drama"], tmdbId: null },
  { id: 42, title: "Mozhi", genres: ["Drama", "Music"], tmdbId: null },
  { id: 43, title: "Ghajini", genres: ["Action", "Thriller"], tmdbId: null },
  { id: 44, title: "Kaakha Kaakha", genres: ["Action", "Thriller"], tmdbId: null },
  { id: 45, title: "Yennai Arindhaal", genres: ["Action", "Mystery"], tmdbId: null },
  { id: 46, title: "Thuppakki", genres: ["Action", "Thriller"], tmdbId: null },
  { id: 47, title: "Vinnaithaandi Varuvaayaa", genres: ["Romance", "Drama"], tmdbId: null },
  { id: 48, title: "Ayan", genres: ["Action"], tmdbId: null },
  { id: 49, title: "Bigil", genres: ["Sports", "Drama"], tmdbId: null },
  { id: 50, title: "Thani Oruvan", genres: ["Action", "Thriller"], tmdbId: null }
];
